"""empty message

Revision ID: 19a7ee3a79bc
Revises: 27a15ed246bd
Create Date: 2023-08-25 09:56:05.064815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a7ee3a79bc'
down_revision = '27a15ed246bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('user_image')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_image')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
