"""empty message

Revision ID: 27a15ed246bd
Revises: 8e5a65c76950
Create Date: 2023-08-25 09:51:37.742570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a15ed246bd'
down_revision = '8e5a65c76950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_post', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('user_image')
        batch_op.drop_column('image_post')

    # ### end Alembic commands ###
