"""empty message

Revision ID: 7688396256c4
Revises: 72a65cbb083e
Create Date: 2023-07-31 18:21:22.974485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7688396256c4'
down_revision = '72a65cbb083e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myreading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('myreading_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'myreading', ['myreading_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('myreading_id')

    op.drop_table('myreading')
    # ### end Alembic commands ###
